name: 'Setup GStreamer'
description: 'Setup GStreamer in the environment'
author: 'Laerdal Labs, DC'
branding:
  color: 'red'
  icon:  'activity'
inputs:
  version:
    description: 'version number'
    required:    false
    default:     '1.18.4'
  arch:
    description: 'architecture (x86, x86_64)'
    required:    false
    default:     'x86_64'
outputs:
  gstreamerPath:
    description: 'Installation path'
runs:
  using: 'node12'
  main: 'dist/index.js'
