name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ['windows', 'macos']
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ['windows', 'macos']
        arch: ['x86', 'x86_64']
        exclude:
          - os:   'macos'
            arch: 'x86'

    steps:
    - uses: actions/checkout@v3

    - name: Setup GStreamer with default version
      id:   setup_gstreamer_default
      uses: ./
      with:
        arch: ${{ matrix.arch }}

    - name: Run gst-inspect --version
      run: |
        gst-inspect-1.0 --version
